### PR TITLE
Add support for VSCode publishing

### PR DESCRIPTION
**Pull request by maia-tae**
We can now publish vscode extensions directly with repo-cooker.

This requires a `publishTo` setting in package.json set to "vscode". The default (if setting is not present) is "npm".

Also fixed commit tag creation during release which prevented github release from executing (at least during my tests).

Some small improvements to the user feedback on skipped executions and whitespace cleanup in release notes.

### CODE REVIEW

**Comment by maia-tae** [comment]
No idea why tests fail on travis. They pass fine on my side...
image

**Comment by henri-hulski** [comment]
> No idea why tests fail on travis. They pass fine on my side...

The first failing test seems to be a timeout problem. Maybe the others also related to that? But doesn't really look like.

**Comment by maia-tae** [comment]
@henri-hulski OK... I fixed the PR, it seems good regarding tests now.

**Comment by henri-hulski** [comment]
Great! PR looks good. :)

**Pull request merged**
